### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by sl0n** [romerojunior/cloudian-api#13]
Hi @romerojunior !

I've just deployed Cloudian cluster in my org, I wonder if  you are still working on this project, willing to accept PRs etc?

Cheers!

**Comment by romerojunior** [comment]
PRs are always welcome! I'm not actively developing this project since it's been stable for my personal needs, but please feel free to test, use or provide new features. 🚀

**Comment by sl0n** [comment]
OK, great, I'm at early stage of it, but keen to take this project as a foundation for any further developments.

Thanks!
